//      -----------------------------------------------------------------------
//      Licensed Materials - Property of IBM
//      IBM Decision Server
//      (c) Copyright IBM Corporation 1987, 2017. All Rights Reserved.
//      RuleApp: BankingRuleapp
//      Date: Apr 20, 2017, 10:36:34 PM
//      Generated by: Decision Server 8.9.0.0
//
//      N O T I C E
//
//      Changes to this file will be lost if the code is regenerated.
//      Note to U.S. Government Users Restricted Rights: 
//      Use, duplication or disclosure restricted by GSA ADP Schedule 
//      Contract with IBM Corp.
//     -----------------------------------------------------------------------

package bankingapp;

import banking_scala_xom.Customer;
import bankingappjava.invocation.CheckCustomerOperationExecution;

/**
 * Entry point of the application
 */
public class Main {

	/**
	 * Execution starts here...
	 */
	public static void main(String[] args) throws Exception {

		CheckCustomerOperationExecution CheckCustomerOperation = new CheckCustomerOperationExecution();
		// TODO insert your code to initialize 'customer'
		
		Customer customer = new Customer(-11);
		CheckCustomerOperation.setCustomer(customer);

		// This method invokes the ruleset 'CheckCustomerOperation'
		CheckCustomerOperation.run();

		// TODO insert your code to handle the response
		System.out.println(CheckCustomerOperation.getCustomer().alerts());

	}

}
