//      -----------------------------------------------------------------------
//      Licensed Materials - Property of IBM
//      IBM Decision Server
//      (c) Copyright IBM Corporation 1987, 2017. All Rights Reserved.
//      RuleApp: BankingRuleapp
//      Date: Apr 20, 2017, 10:36:34 PM
//      Generated by: Decision Server 8.9.0.0
//
//      N O T I C E
//
//      Changes to this file will be lost if the code is regenerated.
//      Note to U.S. Government Users Restricted Rights: 
//      Use, duplication or disclosure restricted by GSA ADP Schedule 
//      Contract with IBM Corp.
//     -----------------------------------------------------------------------

package bankingappjava.invocation;

import ilog.rules.res.session.IlrSessionRequest;
import ilog.rules.res.session.IlrSessionResponse;

/**
 * Wrapper class to facilitate the invocation of ruleset
 * 'CheckCustomerOperation'
 */
public class CheckCustomerOperationExecution extends RulesetExecution {

	private banking_scala_xom.Customer customer;

	/**
	 * Returns the customer
	 */
	public banking_scala_xom.Customer getCustomer() {
		return customer;
	}

	/**
	 * Sets the customer
	 */
	public void setCustomer(banking_scala_xom.Customer customer) {
		this.customer = customer;
	}

	/**
	 * Path to the latest ruleset 'CheckCustomerOperation' in the repository
	 */
	protected String getRulesetPath() {
		return "/BankingRuleapp/1.0/CheckCustomerOperation";
	}

	/**
	 * Initialize the request session with values for input parameters
	 */
	protected void initRequest(IlrSessionRequest request) {
		request.setInputParameter("customer", customer);
	}

	/**
	 * Retrieves values in the response of output parameters
	 */
	protected void handleResponse(IlrSessionResponse response) {
		customer = (banking_scala_xom.Customer) response.getOutputParameters()
				.get("customer");
	}

}
